const Property  = [
  {
    id: 1,
    name: "Luxe Villa",
    status: "for_sale",
    property_type: "house",
    address: "123 Palm Avenue, Koronadal",
    unit_number: "A1",
    bedrooms: 4,
    bathrooms: 3,
    floor_area: 250,
    lot_area: 350,
    amenities: ["Swimming Pool", "Gym", "Garden", "Playground"],
  },
  {
    id: 2,
    name: "Serenity Condo",
    status: "vacant",
    property_type: "condominium",
    address: "456 Sky Tower, Koronadal",
    unit_number: "101",
    bedrooms: 2,
    bathrooms: 1,
    floor_area: 80,
    lot_area: 0,
    amenities: ["Parking", "Security", "Elevator"],
  },
  {
    id: 3,
    name: "Haven Townhouse",
    status: "occupied",
    property_type: "townhouse",
    address: "789 Hillcrest Drive, Koronadal",
    unit_number: "B2",
    bedrooms: 3,
    bathrooms: 2,
    floor_area: 120,
    lot_area: 150,
    amenities: ["Security", "Park", "Playground"],
  },
  {
    id: 4,
    name: "Greenfield Lot",
    status: "for_sale",
    property_type: "lot",
    address: "1010 Green Valley, Koronadal",
    unit_number: "",
    bedrooms: 0,
    bathrooms: 0,
    floor_area: 0,
    lot_area: 500,
    amenities: ["Wide Road Access", "Near School"],
  },
  {
    id: 5,
    name: "Sunrise Residence",
    status: "under_construction",
    property_type: "house",
    address: "1001 Sunrise Road, Koronadal",
    unit_number: "C3",
    bedrooms: 3,
    bathrooms: 2,
    floor_area: 200,
    lot_area: 250,
    amenities: ["Swimming Pool", "Gym", "Community Center"],
  },
  {
    id: 6,
    name: "City Heights Condo",
    status: "occupied",
    property_type: "condominium",
    address: "2002 City Heights, Koronadal",
    unit_number: "402",
    bedrooms: 1,
    bathrooms: 1,
    floor_area: 50,
    lot_area: 0,
    amenities: ["Gym", "Elevator", "Security"],
  },
  {
    id: 7,
    name: "Mountain View Townhouse",
    status: "vacant",
    property_type: "townhouse",
    address: "302 Hilltop Road, Koronadal",
    unit_number: "A5",
    bedrooms: 2,
    bathrooms: 1,
    floor_area: 100,
    lot_area: 120,
    amenities: ["Security", "Parking", "Community Garden"],
  },
];

const Homeowner = [
  {
    id: "H001",
    full_name: "John Doe",
    email: "john.doe@email.com",
    phone: "09171234567",
    property_id: "1",
    unit_number: "A1",
    move_in_date: "2023-04-15",
    emergency_contact_name: "Jane Doe",
    emergency_contact_phone: "09181234567",
    status: "active",
    monthly_dues: 5000,
  },
  {
    id: "H002",
    full_name: "Mary Smith",
    email: "mary.smith@email.com",
    phone: "09189876543",
    property_id: "2",
    unit_number: "101",
    move_in_date: "2023-06-01",
    emergency_contact_name: "Steve Smith",
    emergency_contact_phone: "09187654321",
    status: "inactive",
    monthly_dues: 4500,
  },
];

const ServiceRequest = [
  {
    id: "SR001",
    homeowner_id: "H001",
    property_id: "1",
    request_type: "maintenance",
    title: "Air Conditioner Repair",
    description: "The air conditioner is not working properly.",
    priority: "high",
    status: "pending",
    assigned_to: "John Service",
    scheduled_date: "2023-08-01",
    completed_date: null,
    estimated_cost: 1500,
    actual_cost: null,
    notes: "Awaiting part delivery.",
    attachments: [],
  },
  {
    id: "SR002",
    homeowner_id: "H002",
    property_id: "2",
    request_type: "cleaning",
    title: "Carpet Cleaning",
    description: "Request to clean the carpets in the living room.",
    priority: "medium",
    status: "completed",
    assigned_to: "Mary Cleaning",
    scheduled_date: "2023-07-15",
    completed_date: "2023-07-20",
    estimated_cost: 500,
    actual_cost: 450,
    notes: "Cleaning completed successfully.",
    attachments: [],
  },
];

const Billing = [
  {
    id: "B001",
    homeowner_id: "H001",
    property_id: "1",
    billing_period: "July 2023",
    due_date: "2023-07-15",
    amount: 6000,
    breakdown: {
      association_dues: 5000,
      maintenance_fee: 500,
      utilities: 300,
      penalties: 200,
      other_charges: 0,
    },
    status: "paid",
    payment_date: "2023-07-14",
    payment_method: "bank_transfer",
    receipt_number: "R00123",
  },
  {
    id: "B002",
    homeowner_id: "H002",
    property_id: "2",
    billing_period: "August 2023",
    due_date: "2023-08-10",
    amount: 5500,
    breakdown: {
      association_dues: 4500,
      maintenance_fee: 400,
      utilities: 400,
      penalties: 0,
      other_charges: 0,
    },
    status: "unpaid",
    payment_date: null,
    payment_method: null,
    receipt_number: null,
  },
];

const Complaint = [
  {
    id: "C001",
    homeowner_id: "H001",
    property_id: "1",
    complaint_type: "maintenance",
    subject: "No hot water in shower",
    description: "The shower has no hot water for the last 2 days.",
    severity: "medium",
    status: "investigating",
    assigned_to: "John Maintenance",
    resolution_notes: "",
    resolved_date: null,
    attachments: [],
    follow_up_required: true,
  },
  {
    id: "C002",
    homeowner_id: "H002",
    property_id: "2",
    complaint_type: "security",
    subject: "Broken Gate Lock",
    description: "The gate lock is not functioning properly, making it easy to enter.",
    severity: "high",
    status: "resolved",
    assigned_to: "Steve Security",
    resolution_notes: "Lock was replaced.",
    resolved_date: "2023-08-05",
    attachments: ["gate_lock.jpg"],
    follow_up_required: false,
  },
];

const Announcement = [
  {
    id: "A001",
    title: "Community Pool Maintenance",
    content: "The community pool will be closed for maintenance from August 5 to August 10.",
    category: "maintenance",
    priority: "normal",
    target_audience: "all_residents",
    publish_date: "2023-07-25T10:00:00Z",
    expiry_date: "2023-08-10",
    status: "published",
    attachments: [],
    author: "Admin",
    is_pinned: true,
  },
  {
    id: "A002",
    title: "Security Update",
    content: "Security personnel will be increased during the upcoming holidays for added safety.",
    category: "security",
    priority: "high",
    target_audience: "all_residents",
    publish_date: "2023-07-28T08:00:00Z",
    expiry_date: "2023-08-31",
    status: "draft",
    attachments: [],
    author: "Admin",
    is_pinned: false,
  },
];
const Inquiry = [
  {
    id: 1,
    homeowner_id: "H001",
    name: "John Doe",
    email: "johndoe@example.com",
    phone: "09123456789",
    subject: "Property Information",
    message: "I am interested in more details about the Luxe Villa.",
    category: "property_info",
    status: "pending",
    assigned_to: "Staff A",
    response: "",
    response_date: "",
    priority: "medium",
  },
  {
    id: 2,
    homeowner_id: "H002",
    name: "Jane Smith",
    email: "janesmith@example.com",
    phone: "09234567890",
    subject: "Billing Inquiry",
    message: "Could you clarify the charges on my last bill?",
    category: "billing",
    status: "in_progress",
    assigned_to: "Staff B",
    response: "We are looking into your concern.",
    response_date: "2025-08-25T10:00:00Z",
    priority: "high",
  },
  {
    id: 3,
    homeowner_id: "H003",
    name: "Michael Brown",
    email: "michaelbrown@example.com",
    phone: "09345678901",
    subject: "Amenities Usage",
    message: "I would like to book the swimming pool for a private event.",
    category: "amenities",
    status: "responded",
    assigned_to: "Staff C",
    response: "The swimming pool has been booked for your requested date.",
    response_date: "2025-08-24T15:30:00Z",
    priority: "medium",
  },
  {
    id: 4,
    homeowner_id: null, // Public inquiry
    name: "Alex White",
    email: "alexwhite@example.com",
    phone: "09456789012",
    subject: "General Inquiry",
    message: "Can you provide more information on available properties?",
    category: "general",
    status: "pending",
    assigned_to: "Staff D",
    response: "",
    response_date: "",
    priority: "low",
  },
];

const Reservation = [
  {
    id: 1,
    homeowner_id: "H001",
    facility_name: "clubhouse",
    reservation_date: "2025-09-10",
    start_time: "14:00",
    end_time: "18:00",
    purpose: "Birthday Party",
    expected_guests: 50,
    status: "pending",
    fee: 5000,
    deposit: 2000,
    payment_status: "unpaid",
    special_requests: "Extra chairs and tables",
    approved_by: "",
    approval_date: ""
  },
  {
    id: 2,
    homeowner_id: "H002",
    facility_name: "swimming_pool",
    reservation_date: "2025-09-15",
    start_time: "09:00",
    end_time: "12:00",
    purpose: "Family Gathering",
    expected_guests: 20,
    status: "confirmed",
    fee: 3000,
    deposit: 1000,
    payment_status: "partial",
    special_requests: "Lifeguard on duty",
    approved_by: "Staff A",
    approval_date: "2025-09-01T10:00:00Z"
  },
  {
    id: 3,
    homeowner_id: "H003",
    facility_name: "basketball_court",
    reservation_date: "2025-09-20",
    start_time: "16:00",
    end_time: "20:00",
    purpose: "Friendly Match",
    expected_guests: 30,
    status: "cancelled",
    fee: 1500,
    deposit: 500,
    payment_status: "refunded",
    special_requests: "",
    approved_by: "Staff B",
    approval_date: "2025-09-05T14:30:00Z"
  },
  {
    id: 4,
    homeowner_id: "H004",
    facility_name: "function_hall",
    reservation_date: "2025-09-25",
    start_time: "10:00",
    end_time: "22:00",
    purpose: "Wedding Reception",
    expected_guests: 100,
    status: "completed",
    fee: 10000,
    deposit: 5000,
    payment_status: "paid",
    special_requests: "Stage setup with sound system",
    approved_by: "Staff C",
    approval_date: "2025-09-10T09:00:00Z"
  }
];

const Transaction = [
  {
    id: 1,
    homeowner_id: "H001",
    property_id: "P001",
    transaction_type: "payment",
    reference_id: "RES001",
    reference_type: "reservation",
    amount: 5000,
    description: "Reservation payment for clubhouse",
    payment_method: "gcash",
    receipt_number: "RCPT-1001",
    transaction_date: "2025-09-01T10:30:00Z",
    processed_by: "Staff A",
    status: "completed",
    notes: "Paid in full"
  },
  {
    id: 2,
    homeowner_id: "H002",
    property_id: "P002",
    transaction_type: "billing",
    reference_id: "BILL002",
    reference_type: "billing",
    amount: 3000,
    description: "Monthly association dues",
    payment_method: "bank_transfer",
    receipt_number: "RCPT-1002",
    transaction_date: "2025-09-02T15:00:00Z",
    processed_by: "Staff B",
    status: "pending",
    notes: "Awaiting confirmation"
  },
  {
    id: 3,
    homeowner_id: "H003",
    property_id: "P003",
    transaction_type: "penalty",
    reference_id: "PEN003",
    reference_type: "penalty",
    amount: 500,
    description: "Late payment penalty",
    payment_method: "cash",
    receipt_number: "RCPT-1003",
    transaction_date: "2025-09-03T11:45:00Z",
    processed_by: "Staff C",
    status: "completed",
    notes: "Cleared immediately at office"
  },
  {
    id: 4,
    homeowner_id: "H004",
    property_id: "P004",
    transaction_type: "refund",
    reference_id: "RES004",
    reference_type: "reservation",
    amount: 2000,
    description: "Refund for cancelled pool reservation",
    payment_method: "gcash",
    receipt_number: "RCPT-1004",
    transaction_date: "2025-09-04T09:15:00Z",
    processed_by: "Staff D",
    status: "refunded",
    notes: "Refund processed via GCash"
  },
  {
    id: 5,
    homeowner_id: "H005",
    property_id: "P005",
    transaction_type: "deposit",
    reference_id: "DEP005",
    reference_type: "reservation",
    amount: 3000,
    description: "Security deposit for function hall",
    payment_method: "credit_card",
    receipt_number: "RCPT-1005",
    transaction_date: "2025-09-05T14:20:00Z",
    processed_by: "Staff E",
    status: "completed",
    notes: "Deposit will be refunded after event"
  },
  {
    id: 6,
    homeowner_id: "H006",
    property_id: "P006",
    transaction_type: "fee",
    reference_id: "SR006",
    reference_type: "service_request",
    amount: 1500,
    description: "Maintenance service fee",
    payment_method: "debit_card",
    receipt_number: "RCPT-1006",
    transaction_date: "2025-09-06T13:00:00Z",
    processed_by: "Staff F",
    status: "completed",
    notes: "Paid during request processing"
  }
];


export  {
    Property,
    Homeowner,
    ServiceRequest,
    Billing,
    Complaint,
    Announcement,
    Inquiry,
    Reservation,
    Transaction
}